# Importación de archivos numéricos usando NumPy

>[Importación de archivos numéricos usando NumPy](#scrollTo=ROb15yexpgw2)

>>[Lectura](#scrollTo=XcbNSuGKpkQ-)

>>[Separación por coma (,)](#scrollTo=M__skdJHqIc2)

>>[Archivo con cabecera](#scrollTo=ogEZU_U3p3Cl)

>>[Especificar tipo de dato](#scrollTo=D3-IsAsupy5O)

>>[Aplicar función a columna](#scrollTo=5LHZ5kd6pvRu)

>>[Datos faltantes](#scrollTo=Pevx3uc6pq-H)



## Lectura

In [ ]:
%%writefile /tmp/numpy_data.txt
7.318719402026263587e-02 1.775082190597712106e-01 9.205824952147805273e-01
4.062207718332084827e-01 6.691909950327930012e-01 4.691625868153078693e-01
6.963794427590925817e-01 1.380183788805662282e-01 8.086264398068685466e-01
5.893088349077085786e-01 3.899639085394711602e-01 8.655591960123206752e-01

Writing /tmp/numpy_data.txt


In [ ]:
import numpy as np

In [ ]:
#
# Lectura del archivo de texto
# ===============================================
#
numpy_data = np.loadtxt('/tmp/numpy_data.txt')
numpy_data

array([[0.07318719, 0.17750822, 0.9205825 ],
       [0.40622077, 0.669191  , 0.46916259],
       [0.69637944, 0.13801838, 0.80862644],
       [0.58930883, 0.38996391, 0.8655592 ]])

In [ ]:
#
# Cantidad de datos leidos
#
numpy_data.size

12

## Separación por coma (,)

In [ ]:
%%writefile /tmp/comma_delimited_data.txt
1,2,3
4,5,6
7,8,9
10,11,12

Writing /tmp/comma_delimited_data.txt


In [ ]:
#
# Lectura de un archivo delimitado por comas
# ===============================================
#
numpy_data = np.loadtxt(
    "/tmp/comma_delimited_data.txt",
    delimiter=",",
)
numpy_data

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [ ]:
#
# Selección de columnas a leer
# ===============================================
#
numpy_data = np.loadtxt(
    "/tmp/comma_delimited_data.txt",
    delimiter=",",
    usecols=(0, 2),
)
numpy_data

array([[ 1.,  3.],
       [ 4.,  6.],
       [ 7.,  9.],
       [10., 12.]])

In [ ]:
%%writefile /tmp/comma_delimited_data.txt
col_A,col_B,col_C
1,2,3
4,5,6
7,8,9
10,11,12

Overwriting /tmp/comma_delimited_data.txt


## Archivo con cabecera

Primeras líneas con información diferente a los datos:
- Nombres de las columnas
- Nombre del conjunto de datos

In [ ]:
#
# Lectura de un archivo con cabecera
# ===============================================
#
numpy_data = np.loadtxt(
    "/tmp/comma_delimited_data.txt",
    delimiter=",",
    skiprows=1,
)
numpy_data

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

## Especificar tipo de dato

In [ ]:
#
# Especificación del tipo de dato
# ===============================================
#
numpy_data = np.loadtxt(
    "/tmp/comma_delimited_data.txt",
    delimiter=",",
    skiprows=1,
    dtype=np.uint,
)
numpy_data

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=uint64)

## Aplicar función a columna

In [ ]:
#
# Aplicación de una función a una columna
# ===============================================
#


def increase(id):
    return int(id) + 100


numpy_data = np.loadtxt(
    "/tmp/comma_delimited_data.txt",
    delimiter=",",
    skiprows=1,
    dtype=np.uint,
    converters={0: increase},
)

numpy_data

array([[101,   2,   3],
       [104,   5,   6],
       [107,   8,   9],
       [110,  11,  12]], dtype=uint64)

## Datos faltantes

In [ ]:
%%writefile /tmp/missing_data.txt
1,,3
4,5,6
7,8,
10,11,12

Writing /tmp/missing_data.txt


In [ ]:
#
# Lectura de un archivo con datos faltantes
# ===============================================
#
numpy_data = np.genfromtxt(
    '/tmp/missing_data.txt',
    delimiter=',',
)
numpy_data

array([[ 1., nan,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8., nan],
       [10., 11., 12.]])